baseurl = "/"
relativeurls = true
title = ""
languageCode = "sl-si"
paginate = "10" # Number of posts per page
theme = "Mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id
publishDir = "docs"
pluralizelisttitles = "false"

[Author] # Used in authorbox
    name = "Damjan Dvošek"
    bio = "Damjan's true identity is unknown. Maybe he is a successful blogger or writer. Nobody knows it."
    avatar = ""

[Params]
    bannerImgSrc = "/img/pasica.jpg" # Src path for banner image
    bannerImgAlt = "Društvo prijateljev Ptuja" # Alt text for banner image
    subtitle = "" # Subtitle of your site. Used in site header
    description = " Spletne strani Društva prijateljev Ptuja." # Description of your site. Used in meta description
    opengraph = false # Enable OpenGraph if true
    twitter_cards = false # Enable Twitter Cards if true
    readmore = true # Show "Read more" button in list if true
    leftsidebar = false # Move sidebar to the left side if true
    authorbox = false # Show authorbox at bottom of pages if true
    post_navigation = true # Show post navigation at bottom of pages if true
    postSections = ["novice"] # the section pages to show on home page and the "Recent articles" widget
    #postSections = ["blog", "news"] # alternative that shows more than one section's pages
    #dateformat = "2006-01-02" # change the format of dates



[Params.widgets]
    search = false # Enable "Search" widget
    recent_articles = true # Enable "Recent articles" widget
    recent_articles_num = 5 # Set the number of articles in the "Recent articles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget
    tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)
    preserveTaxonomyNames = true #  if you want to have a taxonomy term with special characters

[menu]
    [[menu.main]]
        Name = "Novice"
        URL = "/novice"
        weight = -6
